
services:
  container_name: reptile
  ports:
    - "8000:8000"
  build: .
  volumes:
    - ./project:/root/project
  tty: true
mysql:
  container_name: mysql
  image: mysql:5.7.16
  ports:
    - "3306:3306"
  volumes:
    - ./mysqlData/:/var/lib/mysql/
  environment:
    MYSQL_ROOT_PASSWORD: "123456" 
