# Generated by Django 2.2.9 on 2020-02-05 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180616_1933'),
        ('accounts', '0002_auto_20200205_0837'),
    ]

    operations = [
    ]
